FROM node:16-alpine as BUILDER
ENV NODE_OPTIONS=--max_old_space_size=128

COPY ./frontend .

RUN npm ci
RUN npm run build

FROM nginx:1.23-alpine
COPY --from=BUILDER /build ./usr/share/nginx/html
COPY nginx-frontend.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
