name: code-validation
on:
  workflow_call:
  push:
    branches:
      - '!master'

jobs:
  frontend:
    uses: ./.github/workflows/test-frontend.yml

  backend:
    uses: ./.github/workflows/test-backend.yml
