name: Test frontend
on: workflow_call
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: Bhacaz/checkout-files@v2
        with:
          files: backend .eslintignore .eslintrc.json

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        with:
          path: ./node_modules/*
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}-frontend

      - name: Install dependencies
        run: npm ci
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        with:
          path: ./node_modules/*
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}-frontend

      - name: eslint validation
        run: npm run lint